package visitor;

import ast.And;
import ast.ArrayAssign;
import ast.ArrayLength;
import ast.ArrayLookup;
import ast.Assign;
import ast.Block;
import ast.BooleanType;
import ast.Call;
import ast.ClassDeclExtends;
import ast.ClassDeclSimple;
import ast.False;
import ast.Formal;
import ast.Identifier;
import ast.IdentifierExp;
import ast.IdentifierType;
import ast.If;
import ast.IntArrayType;
import ast.IntegerLiteral;
import ast.IntegerType;
import ast.LessThan;
import ast.MainClass;
import ast.MethodDecl;
import ast.NewArray;
import ast.NewObject;
import ast.Not;
import ast.Plus;
import ast.Print;
import ast.Program;
import ast.This;
import ast.True;
import ast.VarDecl;
import ast.While;

public interface Visitor {
	public void visit(Program prog);
	public void visit(MainClass main);
	public void visit(ClassDeclSimple simpleClass);
	public void visit(ClassDeclExtends extendsClass);
	public void visit(VarDecl var);
	public void visit(MethodDecl method);
	public void visit(Formal param);
	public void visit(IntArrayType intArrayT);
	public void visit(BooleanType boolT);
	public void visit(IntegerType intT);
	public void visit(IdentifierType idT);
	public void visit(Block blockStm);
	public void visit(If ifStm);
	public void visit(While whileStm);
	public void visit(Print printStm);
	public void visit(Assign assignStm);
	public void visit(ArrayAssign arrayAssignStm);
	public void visit(And andExp);
	public void visit(LessThan lessThanExp);
	public void visit(Plus plusExp);
	public void visit(ArrayLookup arrayLookup);
	public void visit(ArrayLength length);
	public void visit(Call callExp);
	public void visit(IntegerLiteral intLiteral);
	public void visit(True trueLiteral);
	public void visit(False falseLiteral);
	public void visit(IdentifierExp identExp);
	public void visit(This thisLiteral);
	public void visit(NewArray array);
	public void visit(NewObject object);
	public void visit(Not notExp);
	public void visit(Identifier id);
}
